"""add_user_fields

Revision ID: 49d4cb5ef21e
Revises: fc3eb3d38524
Create Date: 2026-07-21 12:53:59.702121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d4cb5ef21e'
down_revision: Union[str, Sequence[str], None] = 'fc3eb3d38524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subjects', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('class_teacher', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'emergency_contact')
    op.drop_column('users', 'address')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'class_teacher')
    op.drop_column('users', 'subjects')
    # ### end Alembic commands ###
