"""add file_id to repository_documents

Revision ID: da5c6ac69084
Revises: f362b8ade1c9
Create Date: 2026-07-22 12:44:21.069596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5c6ac69084'
down_revision: Union[str, Sequence[str], None] = 'f362b8ade1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_documents', sa.Column('file_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_documents', 'file_id')
    # ### end Alembic commands ###
