"""fix_cascade_delete

Revision ID: f362b8ade1c9
Revises: 49d4cb5ef21e
Create Date: 2026-07-21 15:58:12.684800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f362b8ade1c9'
down_revision: Union[str, Sequence[str], None] = '49d4cb5ef21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
