"""initial

Revision ID: fc3eb3d38524
Revises: 
Create Date: 2026-07-21 12:51:50.497487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc3eb3d38524'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_action', 'activity_logs', ['action', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_activity_created', 'activity_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_activity_user', 'activity_logs', ['user_email', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_activity_logs_user_email'), 'activity_logs', ['user_email'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('departments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('school_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('head_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_categories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('school_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['document_categories.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('school_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repository_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('folder_id', sa.String(length=64), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('department_id', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('trashed_at', sa.Float(), nullable=True),
    sa.Column('expiry_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['document_categories.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_repo_docs_favorite', 'repository_documents', ['user_key', 'is_favorite'], unique=False)
    op.create_index('idx_repo_docs_hash', 'repository_documents', ['file_hash'], unique=False)
    op.create_index('idx_repo_docs_user', 'repository_documents', ['user_key', 'status', 'folder_id'], unique=False)
    op.create_table('document_comments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['repository_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_comments_doc', 'document_comments', ['document_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['repository_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_versions_doc', 'document_versions', ['document_id', sa.literal_column('version_number DESC')], unique=False)
    op.alter_column('chat_messages', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('chat_messages', 'sources_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'session_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('chat_sessions', 'user_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.add_column('documents', sa.Column('category_id', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.alter_column('documents', 'file_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('documents', 'user_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('documents', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('documents', 'source_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('documents', 'uploaded_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('documents', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('documents', 'source_ref',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.create_index('idx_documents_category', 'documents', ['category_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'document_categories', ['category_id'], ['id'])
    op.alter_column('file_chunks', 'user_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('file_chunks', 'file_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('file_chunks', 'chunk_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('users', sa.Column('school_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('qualification', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('joining_date', sa.String(length=20), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'user'"))
    op.alter_column('users', 'department',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'employee_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'manager_email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'leave_balance_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('\'{"annual": 20, "sick": 12, "personal": 5}\''))
    op.alter_column('users', 'created_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True)
    op.create_foreign_key(None, 'users', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'created_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False)
    op.alter_column('users', 'leave_balance_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text('\'{"annual": 20, "sick": 12, "personal": 5}\''))
    op.alter_column('users', 'manager_email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'employee_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'department',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'user'"))
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('users', 'joining_date')
    op.drop_column('users', 'qualification')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'school_id')
    op.alter_column('file_chunks', 'chunk_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('file_chunks', 'file_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('file_chunks', 'user_key',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index('idx_documents_category', table_name='documents')
    op.alter_column('documents', 'source_ref',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('documents', 'source',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('documents', 'uploaded_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('documents', 'source_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('documents', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('documents', 'user_key',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('documents', 'file_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'tags')
    op.drop_column('documents', 'category_id')
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'user_key',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'session_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'sources_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('chat_messages', 'role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('idx_doc_versions_doc', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('idx_doc_comments_doc', table_name='document_comments')
    op.drop_table('document_comments')
    op.drop_index('idx_repo_docs_user', table_name='repository_documents')
    op.drop_index('idx_repo_docs_hash', table_name='repository_documents')
    op.drop_index('idx_repo_docs_favorite', table_name='repository_documents')
    op.drop_table('repository_documents')
    op.drop_table('folders')
    op.drop_table('document_categories')
    op.drop_table('departments')
    op.drop_table('schools')
    op.drop_index(op.f('ix_activity_logs_user_email'), table_name='activity_logs')
    op.drop_index('idx_activity_user', table_name='activity_logs')
    op.drop_index('idx_activity_created', table_name='activity_logs')
    op.drop_index('idx_activity_action', table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
